pub const ENV_LOG_LEVEL: &str = "IMGFORGE_LOG_LEVEL";
pub const ENV_KEY: &str = "IMGFORGE_KEY";
pub const ENV_SALT: &str = "IMGFORGE_SALT";
pub const ENV_SECRET: &str = "IMGFORGE_SECRET";
pub const ENV_ALLOW_UNSIGNED: &str = "IMGFORGE_ALLOW_UNSIGNED";
pub const ENV_MAX_SRC_FILE_SIZE: &str = "IMGFORGE_MAX_SRC_FILE_SIZE";
pub const ENV_ALLOWED_MIME_TYPES: &str = "IMGFORGE_ALLOWED_MIME_TYPES";
pub const ENV_MAX_SRC_RESOLUTION: &str = "IMGFORGE_MAX_SRC_RESOLUTION";
pub const ENV_ALLOW_SECURITY_OPTIONS: &str = "IMGFORGE_ALLOW_SECURITY_OPTIONS";
pub const ENV_WORKERS: &str = "IMGFORGE_WORKERS";

pub const ENV_CACHE_TYPE: &str = "IMGFORGE_CACHE_TYPE";
pub const ENV_CACHE_MEMORY_CAPACITY: &str = "IMGFORGE_CACHE_MEMORY_CAPACITY";
pub const ENV_CACHE_DISK_PATH: &str = "IMGFORGE_CACHE_DISK_PATH";
pub const ENV_CACHE_DISK_CAPACITY: &str = "IMGFORGE_CACHE_DISK_CAPACITY";
pub const ENV_WATERMARK_PATH: &str = "IMGFORGE_WATERMARK_PATH";
pub const ENV_PROMETHEUS_BIND: &str = "IMGFORGE_PROMETHEUS_BIND";
