pub const ENV_IMGFORGE_LOG_LEVEL: &str = "IMGFORGE_LOG_LEVEL";
pub const ENV_IMGFORGE_KEY: &str = "IMGFORGE_KEY";
pub const ENV_IMGFORGE_SALT: &str = "IMGFORGE_SALT";
pub const ENV_IMGFORGE_SECRET: &str = "IMGFORGE_SECRET";
pub const ENV_ALLOW_UNSIGNED: &str = "ALLOW_UNSIGNED";
pub const ENV_MAX_SRC_FILE_SIZE: &str = "IMGFORGE_MAX_SRC_FILE_SIZE";
pub const ENV_ALLOWED_MIME_TYPES: &str = "IMGFORGE_ALLOWED_MIME_TYPES";
pub const ENV_MAX_SRC_RESOLUTION: &str = "IMGFORGE_MAX_SRC_RESOLUTION";
pub const ENV_ALLOW_SECURITY_OPTIONS: &str = "IMGFORGE_ALLOW_SECURITY_OPTIONS";
pub const ENV_WORKERS: &str = "IMGFORGE_WORKERS";

pub const CACHE_TYPE: &str = "CACHE_TYPE";
pub const CACHE_MEMORY_CAPACITY: &str = "CACHE_MEMORY_CAPACITY";
pub const CACHE_MEMORY_TTL: &str = "CACHE_MEMORY_TTL";
pub const CACHE_DISK_PATH: &str = "CACHE_DISK_PATH";
pub const CACHE_DISK_CAPACITY: &str = "CACHE_DISK_CAPACITY";
pub const CACHE_DISK_TTL: &str = "CACHE_DISK_TTL";
