name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libvips-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --all -- --test-threads=1
