name: Build & Publish Docker Image(s)

on:
  push:
    branches:
      - dev
      # optionally on tags, PRs etc.

permissions:
  contents: read
  packages: write
  id-token: write   # if you need OIDC or advanced features

jobs:
  build-multiarch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up builder
        run: docker buildx create --use

      - name: Build for ${{ matrix.arch }}
        run: |
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            --output type=registry \
            --tag ghcr.io/imgforger/imgforge:${{ matrix.arch }} .

  merge-manifest:
    needs: build-multiarch
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Merge manifests
        run: |
          docker buildx imagetools create \
            -t ghcr.io/imgforger/imgforge:latest \
            ghcr.io/imgforger/imgforge:amd64 \
            ghcr.io/imgforger/imgforge:arm64

